if(NOT MSVC)
  if (ENABLE_ADDRESS_SANITIZER)
    add_compile_options(-fsanitize=address)
    add_link_options(-fsanitize=address)
    message(STATUS "Enabled Address Sanitizer")
  endif()
  if (ENABLE_UB_SANITIZER)
    add_compile_options(-fsanitize=undefined)
    add_link_options(-fsanitize=undefined)
    message(STATUS "Enabled UB Sanitizer")
  endif()
else()
  message(WARNING "Sanitizers are not supported on MSVC")
endif()
